
name: lime-dev
dependencies:
  - python=3.7.*
  # lime install dependencies
  - matplotlib
  - numpy
  - scipy
  - scikit-learn
  - scikit-image
  # for testing
  - flake8
  - pytest
  # for examples
  - jupyter
  - pandas
  - keras
  - pytorch::pytorch-cpu
  - tensorflow
  - h2oai::h2o
  - py-xgboost
  - torchvision
  - tqdm
#Do seperately pip3 install pydoe2